#### Import Libraries

In [1]:
import keras
import pandas as pd 
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import normalize

#### Load Data

In [2]:
data=pd.read_csv("./Iris.csv")
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

#### Data Pre-processing

In [3]:
data.loc[data["Species"]=="Iris-setosa","Species"]=0
data.loc[data["Species"]=="Iris-versicolor","Species"]=1
data.loc[data["Species"]=="Iris-virginica","Species"]=2
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
0   1            5.1           3.5            1.4           0.2       0
1   2            4.9           3.0            1.4           0.2       0
2   3            4.7           3.2            1.3           0.2       0
3   4            4.6           3.1            1.5           0.2       0
4   5            5.0           3.6            1.4           0.2       0

In [4]:
data=data.iloc[np.random.permutation(len(data))]

In [5]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm Species
120  121            6.9           3.2            5.7           2.3       2
109  110            7.2           3.6            6.1           2.5       2
114  115            5.8           2.8            5.1           2.4       2
80    81            5.5           2.4            3.8           1.1       1
12    13            4.8           3.0            1.4           0.1       0

In [6]:
X=data.iloc[:,1:5].values
y=data.iloc[:,5].values

In [7]:
X

array([[6.9, 3.2, 5.7, 2.3],
       [7.2, 3.6, 6.1, 2.5],
       [5.8, 2.8, 5.1, 2.4],
       [5.5, 2.4, 3.8, 1.1],
       [4.8, 3. , 1.4, 0.1],
       [7.9, 3.8, 6.4, 2. ],
       [5. , 3.6, 1.4, 0.2],
       [6.7, 2.5, 5.8, 1.8],
       [6.1, 2.8, 4.7, 1.2],
       [5.1, 2.5, 3. , 1.1],
       [5.6, 2.8, 4.9, 2. ],
       [5.2, 4.1, 1.5, 0.1],
       [6.2, 3.4, 5.4, 2.3],
       [6.2, 2.2, 4.5, 1.5],
       [6.3, 2.8, 5.1, 1.5],
       [5.1, 3.4, 1.5, 0.2],
       [7.2, 3.2, 6. , 1.8],
       [6.7, 3.3, 5.7, 2.5],
       [5. , 3.5, 1.3, 0.3],
       [5.8, 2.7, 5.1, 1.9],
       [7.6, 3. , 6.6, 2.1],
       [5.7, 3.8, 1.7, 0.3],
       [5. , 3.3, 1.4, 0.2],
       [5.4, 3. , 4.5, 1.5],
       [4.8, 3.4, 1.6, 0.2],
       [6. , 3.4, 4.5, 1.6],
       [6.3, 2.3, 4.4, 1.3],
       [5.4, 3.4, 1.5, 0.4],
       [6.1, 2.6, 5.6, 1.4],
       [7.7, 3. , 6.1, 2.3],
       [5.7, 4.4, 1.5, 0.4],
       [6.4, 3.1, 5.5, 1.8],
       [4.3, 3. , 1.1, 0.1],
       [5. , 2.3, 3.3, 1. ],
       [4.6, 3

In [8]:
y

array([2, 2, 2, 1, 0, 2, 0, 2, 1, 1, 2, 0, 2, 1, 2, 0, 2, 2, 0, 2, 2, 0,
       0, 1, 0, 1, 1, 0, 2, 2, 0, 2, 0, 1, 0, 1, 2, 2, 0, 1, 0, 2, 1, 1,
       2, 2, 2, 1, 1, 1, 1, 1, 0, 2, 1, 0, 0, 1, 1, 1, 0, 2, 2, 0, 2, 2,
       0, 0, 1, 2, 1, 2, 1, 0, 0, 2, 2, 2, 1, 0, 1, 1, 2, 1, 2, 1, 1, 2,
       0, 1, 1, 0, 0, 0, 2, 0, 2, 0, 1, 1, 0, 1, 0, 2, 1, 1, 0, 0, 0, 2,
       0, 1, 0, 1, 1, 2, 1, 0, 0, 1, 0, 2, 2, 2, 1, 2, 2, 0, 1, 1, 2, 1,
       0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0, 1, 0, 2, 2, 2, 1, 1], dtype=object)

In [9]:
X_normalized=normalize(X,axis=0)

In [10]:
X_normalized

array([[0.0954671 , 0.08470916, 0.11215345, 0.13228444],
       [0.09961785, 0.09529781, 0.12002387, 0.14378743],
       [0.08024771, 0.07412052, 0.10034783, 0.13803594],
       [0.07609697, 0.06353187, 0.07476897, 0.06326647],
       [0.0664119 , 0.07941484, 0.02754646, 0.0057515 ],
       [0.10930291, 0.10059213, 0.12592669, 0.11502995],
       [0.06917906, 0.09529781, 0.02754646, 0.01150299],
       [0.09269994, 0.06617903, 0.11412106, 0.10352695],
       [0.08439845, 0.07412052, 0.09247741, 0.06901797],
       [0.07056264, 0.06617903, 0.05902813, 0.06326647],
       [0.07748055, 0.07412052, 0.09641262, 0.11502995],
       [0.07194622, 0.10853361, 0.02951407, 0.0057515 ],
       [0.08578203, 0.09000348, 0.10625064, 0.13228444],
       [0.08578203, 0.05823755, 0.0885422 , 0.08627246],
       [0.08716562, 0.07412052, 0.10034783, 0.08627246],
       [0.07056264, 0.09000348, 0.02951407, 0.01150299],
       [0.09961785, 0.08470916, 0.11805627, 0.10352695],
       [0.09269994, 0.08735632,

In [11]:
total_length=len(data)
train_length=int(0.8*total_length)
test_length=int(0.2*total_length)

X_train=X_normalized[:train_length]
X_test=X_normalized[train_length:]
y_train=y[:train_length]
y_test=y[train_length:]

#### Import neural network modules

In [12]:
from keras.models import Sequential 
from keras.layers import Dense,Activation,Dropout 
from keras.utils import np_utils

#### Build Model

In [13]:
y_train=np_utils.to_categorical(y_train,num_classes=3)
print("y_train",y_train.shape)


y_train (120, 3)


In [14]:
y_test=np_utils.to_categorical(y_test,num_classes=3)
print("y_test",y_test.shape)

y_test (30, 3)


In [15]:
model=Sequential()
model.add(Dense(256,input_dim=4,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 256)               1280      
_________________________________________________________________
dense_1 (Dense)              (None, 128)               32896     
_________________________________________________________________
dense_2 (Dense)              (None, 64)                8256      
_________________________________________________________________
dropout (Dropout)            (None, 64)                0         
_________________________________________________________________
dense_3 (Dense)              (None, 3)                 195       
Total params: 42,627
Trainable params: 42,627
Non-trainable params: 0
_________________________________________________________________


In [17]:
model.fit(X_train,y_train,validation_data=(X_test,y_test),batch_size=20,epochs=10,verbose=1)

Epoch 1/10
6/6 [==============================] - 2s 231ms/step - loss: 1.0927 - accuracy: 0.5607 - val_loss: 1.0788 - val_accuracy: 0.7333
Epoch 2/10
6/6 [==============================] - 0s 11ms/step - loss: 1.0781 - accuracy: 0.6683 - val_loss: 1.0614 - val_accuracy: 0.7333
Epoch 3/10
6/6 [==============================] - 0s 11ms/step - loss: 1.0592 - accuracy: 0.6777 - val_loss: 1.0381 - val_accuracy: 0.7333
Epoch 4/10
6/6 [==============================] - 0s 10ms/step - loss: 1.0387 - accuracy: 0.6819 - val_loss: 1.0080 - val_accuracy: 0.7667
Epoch 5/10
6/6 [==============================] - 0s 10ms/step - loss: 0.9999 - accuracy: 0.7399 - val_loss: 0.9634 - val_accuracy: 0.7333
Epoch 6/10
6/6 [==============================] - 0s 10ms/step - loss: 0.9676 - accuracy: 0.6640 - val_loss: 0.9088 - val_accuracy: 0.7667
Epoch 7/10
6/6 [==============================] - 0s 10ms/step - loss: 0.8927 - accuracy: 0.7250 - val_loss: 0.8304 - val_accuracy: 0.7333
Epoch 8/10
6/6 [==========

In [18]:
prediction=model.predict(X_test)
length=len(prediction)
y_label=np.argmax(y_test,axis=1)
predict_label=np.argmax(prediction,axis=1)

accuracy=np.sum(y_label==predict_label)/length * 100 
print("Dataset accuracy",accuracy )

Dataset accuracy 83.33333333333334


In [19]:
y_test

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [20]:
prediction

array([[0.6891694 , 0.19506961, 0.11576097],
       [0.09664543, 0.33989045, 0.5634641 ],
       [0.06740873, 0.29041746, 0.6421738 ],
       [0.08601676, 0.32316408, 0.5908192 ],
       [0.20522669, 0.40307793, 0.39169544],
       [0.11392829, 0.358042  , 0.52802974],
       [0.10192196, 0.3483503 , 0.54972774],
       [0.7835203 , 0.13900307, 0.07747665],
       [0.2641486 , 0.39548707, 0.34036443],
       [0.16639997, 0.3960383 , 0.43756172],
       [0.0974425 , 0.34222424, 0.56033325],
       [0.13505441, 0.38118324, 0.48376238],
       [0.74826556, 0.16006286, 0.09167154],
       [0.7610334 , 0.15226568, 0.08670085],
       [0.7666759 , 0.14879553, 0.08452856],
       [0.7349778 , 0.16912732, 0.09589486],
       [0.07086373, 0.3009935 , 0.6281428 ],
       [0.19979487, 0.40266103, 0.39754415],
       [0.7863292 , 0.1368472 , 0.07682364],
       [0.7573631 , 0.1549647 , 0.08767223],
       [0.78814286, 0.13512988, 0.07672734],
       [0.08525395, 0.32579216, 0.5889539 ],
       [0.

In [21]:
y_label

array([0, 2, 2, 2, 1, 2, 2, 0, 1, 1, 2, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2,
       0, 1, 0, 2, 2, 2, 1, 1], dtype=int64)